// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowTracker.Data;

#nullable disable

namespace ShowTracker.Data.Migrations
{
    [DbContext(typeof(ShowTrackerDbContext))]
    [Migration("20260325213031_FixErrorWithTheSeasonOfEachEpisode")]
    partial class FixErrorWithTheSeasonOfEachEpisode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EpisodeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeTitle = "1:23:45",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 2,
                            EpisodeTitle = "Please Remain Calm",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/8jv8c8QnXl16rDpD6PEw24kTx5c.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 3,
                            EpisodeTitle = "Open Wide, O Earth",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/6uBlEXw6p7uXJ9VjA36TObgGJE0.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 4,
                            EpisodeTitle = "The Happiness of All Mankind",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/jyqG0vUj8kT8y9JteLoI0lpBT1s.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 5,
                            EpisodeTitle = "Vichnaya Pamyat",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/4rWQK9r0p5momkGumZ5qX6Ch12H.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 6,
                            EpisodeTitle = "Wednesday's Child Is Full of Woe",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 7,
                            EpisodeTitle = "Woe Is the Loneliest Number",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/eYV6G6c5wPLXnw0lPwQBGzb62LF.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 8,
                            EpisodeTitle = "Friend or Woe",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/w0Fao9u1Utn8Hj6kUMlzUxr87hc.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 9,
                            EpisodeTitle = "Woe What a Night",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/6z9XqH0I1GtIsfRSAxEPPYUajF2.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 10,
                            EpisodeTitle = "You Reap What You Woe",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/3sX5Yucs5cjox96D65gis6pZeRA.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 11,
                            EpisodeTitle = "Quid Pro Woe",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/pF3vCtbmZh9rqx8uxFazc2DSES0.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 12,
                            EpisodeTitle = "If You Don't Woe Me by Now",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/jPaz6RtWLpmjHtkobaN6D2PfYZ7.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 13,
                            EpisodeTitle = "A Murder of Woes",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/n8I2c2MvmP0xSg6u40qCMgfHdCq.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 14,
                            EpisodeTitle = "Here We Woe Again",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/1.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 15,
                            EpisodeTitle = "The Devil You Woe",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/2.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 16,
                            EpisodeTitle = "Call of the Woe",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/3.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 17,
                            EpisodeTitle = "If These Woes Could Talk",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/4.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 18,
                            EpisodeTitle = "Hyde and Woe Seek",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/5.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 19,
                            EpisodeTitle = "Woe Thyself",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/6.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 20,
                            EpisodeTitle = "Woe Me The Money",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/7.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 21,
                            EpisodeTitle = "This Means Woe",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/8.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 22,
                            EpisodeTitle = "The Death Row Convict and the Executioner",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/1XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z1.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 23,
                            EpisodeTitle = "Screening and Choosing",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/2XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z2.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 24,
                            EpisodeTitle = "Weakness and Strength",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/3XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z3.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 25,
                            EpisodeTitle = "Hell and Paradise",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/4XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z4.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 26,
                            EpisodeTitle = "The Samurai and the Woman",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/5XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z5.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 27,
                            EpisodeTitle = "Heart and Reason",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/6XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z6.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 28,
                            EpisodeTitle = "Flowers and Offerings",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/7XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z7.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 29,
                            EpisodeTitle = "Student and Master",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/8XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z8.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 30,
                            EpisodeTitle = "Gods and People",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/9XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z9.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 31,
                            EpisodeTitle = "Yin and Yang",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/10XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z10.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 32,
                            EpisodeTitle = "Weak and Strong",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/11XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z11.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 33,
                            EpisodeTitle = "Umbrella and Ink",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/12XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z12.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 34,
                            EpisodeTitle = "Dreams and Reality",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/13XhC3j9w2k6Hf8c7Q3z7Zz0Z0Z13.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 35,
                            EpisodeTitle = "Dawn and Delirium",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a1.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 36,
                            EpisodeTitle = "Reality and Illusion",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a2.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 37,
                            EpisodeTitle = "Immutability and Change",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a3.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 38,
                            EpisodeTitle = "The Samurai Code and Carnage",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a4.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 39,
                            EpisodeTitle = "Humans and Sages",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a5.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 40,
                            EpisodeTitle = "Hindering and Restoration",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a6.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 41,
                            EpisodeTitle = "Two People and One Person",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a7.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 42,
                            EpisodeTitle = "Chrysanthemum and Peach",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a8.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 43,
                            EpisodeTitle = "Love and Karma",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a9.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 44,
                            EpisodeTitle = "Master and Disciple",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a10.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 45,
                            EpisodeTitle = "Ephemeralness and Fire",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a11.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 46,
                            EpisodeTitle = "Episode #2.12",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/a12.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        });
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeasonNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8"),
                            SeasonNumber = 1,
                            ShowId = new Guid("00dcb3bf-6ea7-47d4-bfb9-edd6f48c94a9")
                        },
                        new
                        {
                            Id = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808"),
                            SeasonNumber = 1,
                            ShowId = new Guid("d1c9e5b8-7a0c-4f1e-9b3a-2c8e5f6a7b8c")
                        },
                        new
                        {
                            Id = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27"),
                            SeasonNumber = 2,
                            ShowId = new Guid("d1c9e5b8-7a0c-4f1e-9b3a-2c8e5f6a7b8c")
                        },
                        new
                        {
                            Id = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde"),
                            SeasonNumber = 1,
                            ShowId = new Guid("a2b3c4d5-e6f7-8901-2345-6789abcdef01")
                        },
                        new
                        {
                            Id = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be"),
                            SeasonNumber = 2,
                            ShowId = new Guid("a2b3c4d5-e6f7-8901-2345-6789abcdef01")
                        });
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Show", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00dcb3bf-6ea7-47d4-bfb9-edd6f48c94a9"),
                            Description = "In April 1986, the city of Chernobyl in the Soviet Union suffers one of the worst nuclear disasters in the history of mankind. Consequently, many heroes put their lives on the line in the following days, weeks and months.",
                            IsFavorite = false,
                            Name = "Chernobyl"
                        },
                        new
                        {
                            Id = new Guid("d1c9e5b8-7a0c-4f1e-9b3a-2c8e5f6a7b8c"),
                            Description = "Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability, thwart a killing spree, and solve the mystery that embroiled her parents.",
                            IsFavorite = false,
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-8901-2345-6789abcdef01"),
                            Description = "A squad of prisoners and their guards are sent to investigate a mysterious island. They get stranded there and must rely on each other to survive the island's mysterious and monstrous residents.",
                            IsFavorite = false,
                            Name = "Hell's Paradise"
                        });
                });

            modelBuilder.Entity("ShowTracker.Data.Models.UsersShows", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ShowId");

                    b.HasIndex("ShowId");

                    b.ToTable("UsersShows");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Episode", b =>
                {
                    b.HasOne("ShowTracker.Data.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Season", b =>
                {
                    b.HasOne("ShowTracker.Data.Models.Show", "Show")
                        .WithMany("Seasons")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("ShowTracker.Data.Models.UsersShows", b =>
                {
                    b.HasOne("ShowTracker.Data.Models.Show", "Show")
                        .WithMany("Users")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Show", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
