// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowTracker.Data;

#nullable disable

namespace ShowTracker.Data.Migrations
{
    [DbContext(typeof(ShowTrackerDbContext))]
    [Migration("20260328125506_UpdatedPicturesOfEachEpisode")]
    partial class UpdatedPicturesOfEachEpisode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EpisodeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeTitle = "1:23:45",
                            ImageUrl = "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/21acd328-6298-4928-bb08-e926d776f63d/a53d81424437914d76ce305e1f1c3634b5736dc9.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=320",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 2,
                            EpisodeTitle = "Please Remain Calm",
                            ImageUrl = "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/7c3b4584-c2b1-482f-bc8c-18c91bf1acf1/87eced8d07e3275e259e8e4325e43abac7cc350d.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=320",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 3,
                            EpisodeTitle = "Open Wide, O Earth",
                            ImageUrl = "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/e8d738e3-7bd3-40e5-be1a-d6b2c270064c/f9c7ffb5a19c43ade5b4495cc9ac8613a0831315.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=320",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 4,
                            EpisodeTitle = "The Happiness of All Mankind",
                            ImageUrl = "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/7cc1a700-bd77-456c-9d61-aa95cff7d73b/072b882e161aafb797c01c92f2e3a19b66882e1d.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=320",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 5,
                            EpisodeTitle = "Vichnaya Pamyat",
                            ImageUrl = "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/8d42e46a-0b6d-4acd-85f8-d980ec41769c/0df0fdbb626c582ac918d64a5fb0234a890448dd.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=320",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2019, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8")
                        },
                        new
                        {
                            Id = 6,
                            EpisodeTitle = "Wednesday's Child Is Full of Woe",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRau0OfdR2XiDVJKbosrUguN9E823JJik83QPSbk78xpYSlsuA3ukuo9v2aWKPIHmFCrvcl0kU7jy0mT_FGp1DNg1O0lzZ3VPTrgPhtT4WB2_slAE1osX6d6.webp?r=952",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 7,
                            EpisodeTitle = "Woe Is the Loneliest Number",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABcgZnvtaD-K1zxuS9C5dp6zgPRSBHhSjibTDF56qD51O8W4HTNfs2AFlqwtVYtHQHOeupS0ub9EJsu77-lMXe6jaNrvi7t1QUL8FJgseTYRkM7fM5Tdv_JZ4.webp?r=c99",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 8,
                            EpisodeTitle = "Friend or Woe",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABUDKNEB1pBwnu_RXfzP0xnC4k2cz4HulwQ93P4EwhvqT4FXKKhBpljaO4oiDKFmesn0OJbYmmZbXfMzOahtWq0xoWwY0dMXAPTL1zN2DTcfXDYU0r-cglSt6.webp?r=40b",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 9,
                            EpisodeTitle = "Woe What a Night",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABbv6q4nKAIJ7y7bny28gw_Qc_s9kTfFdA8bdTP003iaiw6OhBjjNOfzfMhOgqD7Vk7t7DvtQU9IVhSexDSkk7o4Hn-QTJPKsAEoayYwVEVqEqflcW2Do3Fip.webp?r=0b4",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 10,
                            EpisodeTitle = "You Reap What You Woe",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABf8Aw8Af3JDmZBdCiS5fNLuiEVIhduj5mxtLIXQFaJak0retmAR0_eIqkCXlC-hu2YMQD8lvNItvPLEBvBdLfV8uefPXan2rgjjRuh0DZeIiduerzGqd7iJS.webp?r=e5d",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 11,
                            EpisodeTitle = "Quid Pro Woe",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZf3PiaLYl-ER8sWFeIw2Z560fzeTQmAPviwt3YnGMxDfLg63g8u6aUmsHZZH2Z4o6SBYIRyZ2PMo3fFtnP26nr6PhVMn7nX5NDP_PJ8_bEpEd3Ezfmofxgv.webp?r=21c",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 12,
                            EpisodeTitle = "If You Don't Woe Me by Now",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABXVM0jmBGYrCi9BUQdr1ExNT9LCJn17WCL9KKp9JuKgH6SzZUFpMl0OacUk7XF4zcVVjuU8RIKVF1TdAJCNYVgErGKgn0WwdNq60WGUoqU_kJVLP3TkUlnIr.webp?r=288",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 13,
                            EpisodeTitle = "A Murder of Woes",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZMlXG39lo4-qufHnTdLwQaeI6ku5GLsIVRI1vL7filQJem5OE3QpVXdHGRQP9AmCnWuD8ebtP4MDGqcSC4PKSE2Uvx_FPe9GisatKLnxoLARbpxiJgKrnK2.webp?r=2e0",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808")
                        },
                        new
                        {
                            Id = 14,
                            EpisodeTitle = "Here We Woe Again",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABaXkU45ZXupNiPrPU8rKYlhydRnhuxOaU5h6Yt2q-Cr3GFtZ0wxgsr0ZA8sxp_AzylnwTAbV2pcVkHv7PNygp1KVpAIb_2-37qW-zLPJR4WlOi_nnmG0IAz9.webp?r=677",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 15,
                            EpisodeTitle = "The Devil You Woe",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZEb-1xChJkJI9ZCXz75XwdSwF-P2n9ScrgvwGbS1fb3LG1BIRnxCmSHw8hgYpE3OIa4Fo-4DQZOoqUeTP5B4OI49QPqLpZCfvICDHLm5Nu1HbhrQR8zMZJx.webp?r=22c",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 16,
                            EpisodeTitle = "Call of the Woe",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABcmSOEcPN1IzcvlzRSZjH-Wr4X_BgRKTITYs4ugqKhA_HXPuC1UzFAxQczq26hLnDSiQF6zzvZsfkd3kpDJ5jmjigw6l0wE_AU45uw_um4pPKgBFMDy9B5MR.webp?r=73b",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 17,
                            EpisodeTitle = "If These Woes Could Talk",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZPcezk8r1htr8czZ76-tMP09NbK3lucW-peokfK592jMEGuJVRZuEPny8-y8ysXdPQBq-C2G9xd7d3TrDcU32VB1-yX8gMYdin4hfHfTUTeKLmbhaLS1eGO.webp?r=2b8",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 18,
                            EpisodeTitle = "Hyde and Woe Seek",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRkhY3pujVZ9oaTqAPHzvBuJ477C_u9Gl3COnlpT88wofxxatd6rsMjGruI-5kImm_AFPu3V0fW8gBS_J-1yRFSXTBnprKqgaQquVRWM2SrzH8PQWqDuo-6u.webp?r=a42",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 19,
                            EpisodeTitle = "Woe Thyself",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABVyOcT09gIvsvmjeFrx4CdiY8vd277poyEgOxGQz_4SE-MXcYuFjwCPYJjKXp4TvxQ1L59C8jUPxzcBoBRmc4Vveh6FZv3AzrEHv-ttnon53we4RWvkZ66AR.webp?r=069",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 20,
                            EpisodeTitle = "Woe Me The Money",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABVLMhYFs43xmPdceyhVIahmCgWeT6CXiI835RV1kXzKKNsG03YlwoUWeSkIxGYegKxMcOIzw1fFrcWQXE6mKr4tYb9P6ktUvtRbYa0e24fqfA0tRASfavopC.webp?r=d3c",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 21,
                            EpisodeTitle = "This Means Woe",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRRYxyq9yQHM2oUDbOKMWwG1-rKXFh0CY5Cb3oG7EBiRK2rStjLQYGKo1-cZd1Rzn1jz9GZPJ4TSf9BZoSoqmx9WbGtbMpIIL2NPPSEa8aHNTmxq4zsTfIH-.webp?r=3cd",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27")
                        },
                        new
                        {
                            Id = 22,
                            EpisodeTitle = "The Death Row Convict and the Executioner",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZ4Fp6QfStTjje80wxPS_or1bQd0FXCn3BMZFNLTGmtga_LhQgVvuFOpxFDBG3ZDEbf9l0Hg3mTHnC6PE4A6soZawwZ-crB_vChv6N_08HVAy0okT8l2lxYt.webp?r=fc3",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 23,
                            EpisodeTitle = "Screening and Choosing",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABcBTzuAj_vSaHDnIqW5MjWc__KAM_NgexKN6I3k4iaXPicwiR-KQzy1yIUt73hjMieEFNYkHM6HPnkiQus66eqoOiR61b6zF3rHKtwRcQKrB6s00uQB-2T_v.webp?r=fab",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 24,
                            EpisodeTitle = "Weakness and Strength",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABa2UG7nvU1KTg8nRVkZDUlMX-mEfdZfAOOzJQJrk4mjIvRYVPYtzHfP-wmkDuBobBnicCBG0zj0FodEHkvU8W3h-9HO9rDy6CmfMAY-hSnpEb9bvuc_l2MKB.webp?r=6c0",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 25,
                            EpisodeTitle = "Hell and Paradise",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABQzgqr2llHi9H31hsVqc2Zpy21LyPVPqF6TejdZvVD13ypgcAl5eMtVrO5fwiqIRUejC2VSe29uOatbZyPo2BnGpa7nTqXtl-21oeAaG2QeryNkPqs1mcUGh.webp?r=a86",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 26,
                            EpisodeTitle = "The Samurai and the Woman",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABXh76nHg4o1CXASqP_clIBTdx0Fkk6dLhLE6DJ-zSq_5su0-sLn9TJ8wVnVauB1TlLTX7_UvqqqJC7mYZ7R9pESkNhTPru1B2flvlPFyg6tweRev_D4AUoBS.webp?r=8bb",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 27,
                            EpisodeTitle = "Heart and Reason",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABfapnc9qA3dfSkpNNNllsxS0tTTcqQ0Yy0pv5UmS1lRzQRMzxSkbvyVHgRqcMY6iSVpLjhIkrc8Z-GT4BEjZrls9U2jGctSDNLGwZmIoaUyEdDqVK56c9p6g.webp?r=394",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 28,
                            EpisodeTitle = "Flowers and Offerings",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABU4dzDDdtsTASc-LrwfcfjfnPKPoOr57MTb7U4YMMWwYlEtiU7b4kZlgFoOlKp0TTYBxw7wBwYjJzklTV3imArYIF0KhqIbsdBFb1MA5PKgIcFYNBjh-cLXX.webp?r=e8a",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 29,
                            EpisodeTitle = "Student and Master",
                            ImageUrl = "https://occ-0-6484-3467.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABVVv3wLdl-1UKOdzagRzOIrwvMALEWSB-uIyE9PmlnScku9_OB8Q2Tjf9lgH5aTj60vfLHo7J-HoNuFy5Ux_ZEg8Gf-Y6jqoU6gU5CCooPVfYMRI6OifcKHZ.webp?r=7f6",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 30,
                            EpisodeTitle = "Gods and People",
                            ImageUrl = "https://resizing.flixster.com/n91pgJMgin35WqlPC5hd7VyBH2M=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p24743367_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 31,
                            EpisodeTitle = "Yin and Yang",
                            ImageUrl = "https://resizing.flixster.com/pbNvgvuGRcNZhZefvhzgM3wC8KA=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p24857692_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 32,
                            EpisodeTitle = "Weak and Strong",
                            ImageUrl = "https://resizing.flixster.com/WlpgXAA-NB960yZwQlBfk2vO1Xg=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p24857696_e_h10_ab.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 33,
                            EpisodeTitle = "Umbrella and Ink",
                            ImageUrl = "https://resizing.flixster.com/4ujEIiHMlz1pAt9dW7nDOcLxt_k=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p24857701_e_h10_ab.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 34,
                            EpisodeTitle = "Dreams and Reality",
                            ImageUrl = "https://resizing.flixster.com/07LXBRb-Qh69cdaZhVM7wxATHG8=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p24509505_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde")
                        },
                        new
                        {
                            Id = 35,
                            EpisodeTitle = "Dawn and Delirium",
                            ImageUrl = "https://resizing.flixster.com/gWATwvDMoCBO6RCoslZdjuQcfus=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p31864210_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 36,
                            EpisodeTitle = "Reality and Illusion",
                            ImageUrl = "https://resizing.flixster.com/_QM8qaO9b9hy7VvlamBnIeiNOSc=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p32032077_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 37,
                            EpisodeTitle = "Immutability and Change",
                            ImageUrl = "https://resizing.flixster.com/Bv2ok4Vydt3GGZ5TmzXaFisfCDs=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p32032078_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 38,
                            EpisodeTitle = "The Samurai Code and Carnage",
                            ImageUrl = "https://resizing.flixster.com/wxn4iO5Fc5xlb0_s3SG0jumAXSU=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p32032079_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 39,
                            EpisodeTitle = "Humans and Sages",
                            ImageUrl = "https://resizing.flixster.com/io6pBBjMHjXxiicmwRgPamc3KUM=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p32032080_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 40,
                            EpisodeTitle = "Hindering and Restoration",
                            ImageUrl = "https://resizing.flixster.com/2XYMzMtz1MepmLQgBoQAuYrF8jY=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p32032081_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 41,
                            EpisodeTitle = "Two People and One Person",
                            ImageUrl = "https://resizing.flixster.com/WZhJhlnZVv_paJN2B60icqx-dIg=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p32032082_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 42,
                            EpisodeTitle = "Chrysanthemum and Peach",
                            ImageUrl = "https://resizing.flixster.com/eNZMj52gB3hog563e8MofsRSqDU=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p32032083_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 43,
                            EpisodeTitle = "Love and Karma",
                            ImageUrl = "https://resizing.flixster.com/dhmGxLNsRAI0YfayOO0xW1LXhlg=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p32032084_e_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 44,
                            EpisodeTitle = "Master and Disciple",
                            ImageUrl = "https://resizing.flixster.com/Xe5sS_qGYTm5lm1iwOEHx-QCTs4=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p31595321_i_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 45,
                            EpisodeTitle = "Ephemeralness and Fire",
                            ImageUrl = "https://resizing.flixster.com/Xe5sS_qGYTm5lm1iwOEHx-QCTs4=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p31595321_i_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        },
                        new
                        {
                            Id = 46,
                            EpisodeTitle = "Episode #2.12",
                            ImageUrl = "https://resizing.flixster.com/Xe5sS_qGYTm5lm1iwOEHx-QCTs4=/370x208/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p31595321_i_h10_aa.jpg",
                            IsWatched = false,
                            ReleaseDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be")
                        });
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeasonNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d46740-7c4b-4380-8122-adee43c370e8"),
                            SeasonNumber = 1,
                            ShowId = new Guid("00dcb3bf-6ea7-47d4-bfb9-edd6f48c94a9")
                        },
                        new
                        {
                            Id = new Guid("0f390bd4-7a7d-4ed2-92a7-6db49306f808"),
                            SeasonNumber = 1,
                            ShowId = new Guid("d1c9e5b8-7a0c-4f1e-9b3a-2c8e5f6a7b8c")
                        },
                        new
                        {
                            Id = new Guid("9c524886-a88e-49b3-a510-025b76f4cf27"),
                            SeasonNumber = 2,
                            ShowId = new Guid("d1c9e5b8-7a0c-4f1e-9b3a-2c8e5f6a7b8c")
                        },
                        new
                        {
                            Id = new Guid("64b81beb-e7dc-409e-a004-0cd2d0442cde"),
                            SeasonNumber = 1,
                            ShowId = new Guid("a2b3c4d5-e6f7-8901-2345-6789abcdef01")
                        },
                        new
                        {
                            Id = new Guid("87932afe-1b94-46e6-83a3-034b0aa183be"),
                            SeasonNumber = 2,
                            ShowId = new Guid("a2b3c4d5-e6f7-8901-2345-6789abcdef01")
                        });
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Show", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00dcb3bf-6ea7-47d4-bfb9-edd6f48c94a9"),
                            Description = "In April 1986, the city of Chernobyl in the Soviet Union suffers one of the worst nuclear disasters in the history of mankind. Consequently, many heroes put their lives on the line in the following days, weeks and months.",
                            IsFavorite = false,
                            Name = "Chernobyl"
                        },
                        new
                        {
                            Id = new Guid("d1c9e5b8-7a0c-4f1e-9b3a-2c8e5f6a7b8c"),
                            Description = "Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability, thwart a killing spree, and solve the mystery that embroiled her parents.",
                            IsFavorite = false,
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-8901-2345-6789abcdef01"),
                            Description = "A squad of prisoners and their guards are sent to investigate a mysterious island. They get stranded there and must rely on each other to survive the island's mysterious and monstrous residents.",
                            IsFavorite = false,
                            Name = "Hell's Paradise"
                        });
                });

            modelBuilder.Entity("ShowTracker.Data.Models.UsersShows", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ShowId");

                    b.HasIndex("ShowId");

                    b.ToTable("UsersShows");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Episode", b =>
                {
                    b.HasOne("ShowTracker.Data.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Season", b =>
                {
                    b.HasOne("ShowTracker.Data.Models.Show", "Show")
                        .WithMany("Seasons")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("ShowTracker.Data.Models.UsersShows", b =>
                {
                    b.HasOne("ShowTracker.Data.Models.Show", "Show")
                        .WithMany("Users")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("ShowTracker.Data.Models.Show", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
